name: lab_3
description: A music player.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  audioplayers: ^1.1.1
  auto_size_text: ^3.0.0
  external_path: ^1.0.3
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_breadcrumb: ^1.0.1
  flutter_neumorphic: ^3.2.0
  metadata_god: ^0.3.1
  path: ^1.8.2
  permission_handler: ^9.2.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
