name: lab_2
description: A simple calculator.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.3.4"

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  flutter_neumorphic: ^3.2.0
  line_icons: ^2.0.1
  math_expressions: ^2.3.1
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
