name: lab_2
description: A simple calculator.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.3.4"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
